<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snowflake.proto

namespace Delz\Snowflake;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *生成Snowflake输入参数
 * </pre>
 *
 * Protobuf type <code>delz.snowflake.SnowflakeRequest</code>
 */
class SnowflakeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *业务Id
     * </pre>
     *
     * <code>int64 serviceId = 1;</code>
     */
    private $serviceId = 0;
    /**
     * <pre>
     *返回数据格式
     * </pre>
     *
     * <code>string format = 2;</code>
     */
    private $format = '';

    public function __construct() {
        \Delz\Snowflake\GPBMetadata\Snowflake::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *业务Id
     * </pre>
     *
     * <code>int64 serviceId = 1;</code>
     */
    public function getServiceId()
    {
        return $this->serviceId;
    }

    /**
     * <pre>
     *业务Id
     * </pre>
     *
     * <code>int64 serviceId = 1;</code>
     */
    public function setServiceId($var)
    {
        GPBUtil::checkInt64($var);
        $this->serviceId = $var;
    }

    /**
     * <pre>
     *返回数据格式
     * </pre>
     *
     * <code>string format = 2;</code>
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * <pre>
     *返回数据格式
     * </pre>
     *
     * <code>string format = 2;</code>
     */
    public function setFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->format = $var;
    }

}

