<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snowflake.proto

namespace Delz\Snowflake\GPBMetadata;

class Snowflake
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad6010a0f736e6f77666c616b652e70726f746f120e64656c7a2e736e6f" .
            "77666c616b6522350a10536e6f77666c616b655265717565737412110a09" .
            "736572766963654964180120012803120e0a06666f726d61741802200128" .
            "09221c0a0e536e6f77666c616b655265706c79120a0a0269641801200128" .
            "0932560a09536e6f77666c616b6512490a0347656e12202e64656c7a2e73" .
            "6e6f77666c616b652e536e6f77666c616b65526571756573741a1e2e6465" .
            "6c7a2e736e6f77666c616b652e536e6f77666c616b655265706c79220062" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

